### ISSUE TITLE
Support of .NET Core 

### ISSUE THREAD

**Issue by netspark** [SharpMap/SharpMap#38]
Is there any plan to port library to new vertion of C# and support .NET Core?

**Comment by FObermaier** [comment]
There is currently no plan for it.
We'd have to wait for other core libraries to be ported to .NET Core, most prominent NetTopologySuite

**Comment by am2222** [comment]
I think sharpmaps development is not as active as before. And also I think it some how NetTopologySuite and Sharpmap join it will be a great one, Sharp map can handle most of viewing operations well and NetTopologySuite can handle other side well

**Comment by becio** [comment]
Lots of types in _System.Drawing_ namespace used by SharpMap are not included in .NET Core 2, so no luck.

The rendering pipeline must be rewritten first, _Branches_TrunkRenderingRefactoring_ is an old attempt.

**Comment by StuffOfInterest** [comment]
Was just looking to see what it will take to target SharpMap at .NET Standard.  The two libraries referenced by the core SharpMap project (GeoAPI and NetTopologySuite) both have "pre" versions out that support .NET Standard (https://www.nuget.org/packages/GeoAPI/1.7.5-pre020 and https://www.nuget.org/packages/NetTopologySuite/1.15.0-pre063).  As I mentioned back in February, the Windows Comparability Pack supports much of the drawing API (see https://www.nuget.org/packages/System.Drawing.Common/ for the core of it).  Those libraries came out of preview and release candidate state a month ago with .NET Core 2.1 was released.

At a glance, I don't see any blockers towards starting to move libraries over to .NET Standard from the bottom up.   First step would be to change the .NET Framework version to one that can consume .NET Standard 2.0 (I believe 4.6.1 is the minimum version there).  After that it is a matter of working from the bottom up to change over from .NET Framework to .NET Standard in the project targets.

I'm in the middle of converting a large code base from .NET Framework to .NET Core (with shared libraries targeting .NET Standard).  SharpMap has become a blocker for me in porting several parts of the code.  At this point I'm trying to figure out if it will be easier to update SharpMap or find a replacement that can be used with .NET Standard.

**Comment by FObermaier** [comment]
This has been neglected for quite a while:
Please have a look at the [refactor/netStandard](https://github.com/SharpMap/SharpMap/tree/refactor/netStandard) branch, especially this commit: f803e7997df34a56ee70deca6b0a4e96ac43dd4a

An initial package can be tested:
* [SharpMap.1.2.0-pre1.nupkg.zip](https://github.com/SharpMap/SharpMap/files/2374017/SharpMap.1.2.0-pre1.nupkg.zip)
* [SharpMap.Layers.BruTileLayer.1.2.0-pre1.nupkg.zip](https://github.com/SharpMap/SharpMap/files/2375000/SharpMap.Layers.BruTileLayer.1.2.0-pre1.nupkg.zip)

**Comment by StuffOfInterest** [comment]
Very glad to hear that this is back in action!  I'm trying to integrate the package above into my project now.  Unfortunately, I'm running into an issue.  It looks like I need the "SharpMap.Layers.BruTile" project to get this working right.  I see you have been doing updates there so hopefully it has been updated for .NET Standard.

Any chance you can spin out a NuGet package for that project?  Otherwise, I'll try cloning the branch and see if I can get the packages to build for myself.

UPDATE

Nevermind on the BruTile project.  All I needed from there was one file, TileLayer.cs, for which I was able to copy the source over to my project.  I was able to compile my project with .NET Framework 4.7.1 after a few updates for namespace changes and one object name change in BruTile.  If I can carve off some time I'll try to convert over to .NET Standard and get everything running.

**Comment by StuffOfInterest** [comment]
It looks like something is not happy in the library.

I have this unit test:

```
[TestMethod]
public void CanCreateMapObject()
{
    // Arrange
    var size = new Size(100, 100);

    // Act
    var map = new SharpMap.Map(size);

    // Assert
    Assert.IsNotNull(map);

    // Cleanup
    map.Dispose();
}
```

It is generating the following error:

```
System.TypeInitializationException: The type initializer for 'SharpMap.Map' threw an exception. ---> System.InvalidOperationException: Cannot use GeometryServiceProvider without an assigned IGeometryServices class
    at GeoAPI.GeometryServiceProvider.InitializeInstance() in C:\TeamCity\BuildAgent\work\16dae4de5d9de063\src\GeoAPI\GeometryServiceProvider.cs:line 147
   at SharpMap.Map..cctor()
--- End of inner exception stack trace ---
    at SharpMap.Map..ctor(Size size)
   at Mapping.Tests.MapFactoryTests.CanCreateMapObject() in C:\Users\me\Source\Repos\Mapping\Mapping.Tests\MapFactoryTests.cs:line 86
```

Perhaps something changed in GeoAPI.

Not sure if it would be of help but I did find reference to the error here:

https://github.com/NetTopologySuite/NetTopologySuite/issues/189

It appears to have something to do with assembly scanning under .NET Standard.

UPDATE (again)

It appears that this error can be stopped by running this before trying to create a Map object:

```
NetTopologySuiteBootstrapper.Bootstrap();
```

Seems like this should be taken care of by the library instead of the end consumer having to bootstrap it.

With that fix, I have my project converted over to target .NET Standard 2.0 and a couple of dozen unit tests exercising it.  Looks like the conversion is pretty good.  Thanks!

**Comment by StuffOfInterest** [comment]
I've been continuing to work on integrating the .NET Standard version of SharpMap into my .NET Core application.  Work has now moved beyond just unit tests to actually building maps.  So far, I'm able to add tile layers to the map and generate an image for a bounded section of a map.  Only headache I had here was the change from "BoundingBox" to "Envelope" when invoking the "ZoomToBox" method.  The two objects work the same, but the order of the parameters in the constructor are different!

The problem I'm having now is in trying to add a vector layer into the map to present markers at set coordinates.  The code runs but all I ever get is a big red X covering the entire map.  I've documented the issue over on StackExchange (https://gis.stackexchange.com/questions/297110/add-marker-with-sharpmap-using-vectorlayer) as it seems beyond scope of this issue and may be more of an implementation problem on my part.

**Comment by FObermaier** [comment]
@StuffOfInterest I suppose it is related to #115.
The provided solution should be usable for the netStandard branch as well.

**Comment by StuffOfInterest** [comment]
Interesting that the exception is swallowed and just rendered as a red box instead of bubbling up an exception.  Still, if this fixes it then great.  Let me know when you merge over the commit to the net standard branch and cut a new package.  I can test it out pretty quickly as I'm actively working around that code for a few more days.

**Comment by StuffOfInterest** [comment]
Was the refactor/netstandard branch merged into the master?  I don't see it out there anymore.  If it was, any idea on when a release may be coming out?  I'm getting closer to using this in a project and the customer really doesn't like seeing things like "-pre1" in dependency versions.

**Comment by FObermaier** [comment]
It has been merged into Branches/1.0
For the timeline of v1.2 I can't make any promises.

**Comment by StuffOfInterest** [comment]
Some good news, I pulled down the source and built my own package from the 1.0 branch.  The issue with the red box I reported earlier and you thought was part of #115 is gone and my marker is rendering now.  Thanks.

**Comment by groege** [comment]
Hey,
Is there a working NuGet package online?
Thanks.

**Comment by UbhiTS** [comment]
+1, can we please a net standard 2.0 supporting nuget package ?

**Comment by FObermaier** [comment]
Fixed
