### ISSUE TITLE
Rendering Issue with moving marker on VariableLayers 

### ISSUE THREAD

**Issue by hcs3389** [SharpMap/SharpMap#61]
Hi, I am new to SharpMap. I am trying to add a marker and making it move. It renders properly when i don't do any panning or zooming but the marker disappears whenever I zoom in or when I pans the map. The marker will reappear when i zoom out. It doesn't seems to be the MinVisible/MaxVisible settings as I have tried setting the MinVisible to 0 and MaxVisible to a high value. Attached is my sample program. 
[MiniMap.zip](https://github.com/SharpMap/SharpMap/files/1117341/MiniMap.zip)
 May I know how to fix this issue? Thanks

**Comment by ThomasN-Saab** [comment]
Without looking at your sample program (I simply don't have the time right now, sorry) this sounds a lot like a problem that I've had for a very long time and just solved.

In my situation I have a VectorLayer which uses a GeometryProvider as datasource. I found that the issue was that the underlaying geometry in the GeometryProvider wasn't updated with the VectorLayer, yet for some reason the VectorLayer uses this geometry to check whether to be culled or not. That means that you have to have the geometry's original position in view for the VectorLayer to render.

The solution that I found was to update the underlaying geometry everytime I make a change to the VectorLayer. 'myGeometryProvider' in this case is the datasource of the VectorLayer in question:
`myGeometryProvider.Geometries[0].GeometryChanged();`

This function notifies the geometry that changes has been made, as stated in the function's summary:
`// Summary:`
`//     Notifies this geometry that its coordinates have been changed by an external`
`//     party (using a CoordinateFilter, for example). The Geometry will flush and/or`
`//     update any information it has cached (such as its GeoAPI.Geometries.IEnvelope).`

Frankly, having to manually tell each geometry in a VectorLayer to update itself after changes are made is just ridiculous. If it renders properly then it should be safe to assume that the envelope that is checked when culling is updated properly too. Sadly, it's a common problem with open source projects that documentation is lacking and questions by us who are ignorant goes unanswered.

**Comment by FObermaier** [comment]
The observation that, when changing a geometries coordinate data, you have to call `geometry.GeometryChanged()` in order to update the geometries envelope, is correct.
