### ISSUE TITLE
MapBox disabling CustomTool in OnActiveToolChanging

### ISSUE THREAD

**Issue by terribletim** [SharpMap/SharpMap#65]
MapBox [OnActiveToolChanging](https://github.com/SharpMap/SharpMap/blob/Branches/1.0/SharpMap.UI/Forms/MapBox.cs#L706) temporarily disables an active custom tool.

However, this is not re-enabled during [OnActiveToolChanged](https://github.com/SharpMap/SharpMap/blob/Branches/1.0/SharpMap.UI/Forms/MapBox.cs#L719)

Should **OnActiveToolChanged** be modified to re-enable a custom tool, such as:

     protected virtual void OnActiveToolChanged(Tools activeTool)
        {
            if (CustomTool != null && activeTool == Tools.Custom )
                CustomTool.Enabled = true;

            var handler = ActiveToolChanged;
            if (handler != null)
                handler(activeTool);
        }

Thanks
TT

**Comment by becio** [comment]
I confirm, moreover I do not see any reason why the MapBox should disable the CustomTool, that property should be used only by devs for their use.

**Comment by terribletim** [comment]
Thanks. I shall submit a pull request when I'm back in the code next week. 

I was also a bit confused at first by OnActiveToolChanging disabling CustomTool. However, it is required when the map has multiple toolbars, otherwise you can end up with multiple tools appearing to be enabled.

**Comment by becio** [comment]
I confirm there is something wrong, but I am not sure about your solution. 

The original problem which led to the disable assignment, as stated by its author in the comment, was that if you have a CustomTool assigned and then after you set the ActiveTool to a standard action, eg Pan, then the MapBox still considers the custom tool active, but this could be solved by simply resetting that property before setting the Pan, or with this fix:

`private bool UseCurrentTool { get { return _currentTool != null && _currentTool.Enabled && ActiveTool == Tools.Custom; }}`

The author added the feature that the MapBox should disable the old tool, but as we see he also added a problem, because the tool remains disabled, The code in CustomTool property is buggy as well, it does not raise the _ActiveToolChanging_ event, which I think prevents anyway the disabling of the old tool.

The only scenario I can think of is with a UI control that manages multiple buttons, where only a single one can be active, well, setting the state enabled/disabled should not be the role of such container/manager?

I think the proper solution is to remove this responsability from the MapBox control, and keep the things simple and flexible. If a dev wants to managed the state of the tools from within the MapBox he could intercept the tool-changed events to add it back.

**Comment by terribletim** [comment]
OK - let me take another look when I'm back in the code and get back to you.

**Comment by FObermaier** [comment]
@becio just curious, have you taken any action solving this issue that is available in the repository?

**Comment by becio** [comment]
Unfortunatelly I do not have much time, anyway I did some tests, the quickest fix is to apply the patch from @terribletim, that is in fact the code I am currently using.

The method _UseCurrentTool_ can be kept as it is now, since the tool can be enabled only when it is active as long as external code do **not** modify the enabled value of the tool.

As I stated in the previous note, since external code could eventually use the Enabled property, I think it is better to remove the setter from the IMapTool interface, anyway since it is a breaking change we can do it later and discuss of it in a separate issue.

**Comment by FObermaier** [comment]
So we can merge @terribletim 's pull request or just part of it?
`CustomTool`et. al. has not been in the released v1.1 package, so -imho- we can do with the setter whatever we like.

**Comment by terribletim** [comment]
@FObermaier I haven't yet submitted above as a pull request, but since there seems to be general consensus that this is ok for the time being I will submit PR later today.

I do have an outstanding pull request consisting of 3 commits. I will follow up on this separately later today on original thread.
